# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gup < Formula
  desc "gup - Update binaries installed by 'go install'"
  homepage ""
  version "1.1.3"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/gup/releases/download/v1.1.3/gup_1.1.3_darwin_amd64.tar.gz"
      sha256 "7d62a267aedb94ab1fb75b772cd0aea7f0c90267dc69d97bcde15df086dd5c07"

      define_method(:install) do
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/gup/releases/download/v1.1.3/gup_1.1.3_darwin_arm64.tar.gz"
      sha256 "aedef79ac9dc60f2e912cb3b9fd92f654e3024dc84bc425a4ea2b34e9d7b24b8"

      define_method(:install) do
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/gup/releases/download/v1.1.3/gup_1.1.3_linux_amd64.tar.gz"
      sha256 "01526e161ad4f6f4e615f5f425a63d37b22f79b6afea04ce72dad2fa73c4925d"
      define_method(:install) do
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/gup/releases/download/v1.1.3/gup_1.1.3_linux_arm64.tar.gz"
      sha256 "a38688e72ede2bf28bf743472353c91781bc1f1ad83bc3c0ce5b48c40ed91279"
      define_method(:install) do
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
  end
end
