# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gup < Formula
  desc "gup - Update binaries installed by 'go install'"
  homepage ""
  version "0.27.9"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/gup/releases/download/v0.27.9/gup_0.27.9_darwin_amd64.tar.gz"
      sha256 "382b1070b77eedeb724ead8adb7455967a635402849a2616ce6764273a13dd66"

      def install
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/gup/releases/download/v0.27.9/gup_0.27.9_darwin_arm64.tar.gz"
      sha256 "4419daf72a31e3237270d0cf0ef559e58ac01ed3d3247e3a30b2143456c09ccf"

      def install
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/gup/releases/download/v0.27.9/gup_0.27.9_linux_amd64.tar.gz"
      sha256 "47d0cb226cac9275a101bda4977eaca37eb1c9a3b5f1cabcba8b86e8e0b86bbe"
      def install
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/gup/releases/download/v0.27.9/gup_0.27.9_linux_arm64.tar.gz"
      sha256 "22db17177ecdf89970f1c13b777d9bc3406d774cfd4bf1d30b2585ca2a2a19d1"
      def install
        bin.install "gup"
        bash_completion.install "completions/gup.bash" => "gup"
        zsh_completion.install "completions/gup.zsh" => "gup"
        fish_completion.install "completions/gup.fish"
      end
    end
  end
end
