# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honeycomb < Formula
  desc "honeycomb - Nostr client CLI application for cross-platform"
  homepage ""
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nao1215/honeycomb/releases/download/v0.0.1/honeycomb_0.0.1_darwin_amd64.tar.gz"
      sha256 "c66fc62800245954fbb7ead392a5033c0d965d19bb91642cd2a9410b760df7d7"

      def install
        bin.install "honeycomb"
      end
    end
    on_arm do
      url "https://github.com/nao1215/honeycomb/releases/download/v0.0.1/honeycomb_0.0.1_darwin_arm64.tar.gz"
      sha256 "62823fc0f0b57e09cd18967e55e9b32126bfbb3a2ce0f7f74c0e0c7d5aaba548"

      def install
        bin.install "honeycomb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/honeycomb/releases/download/v0.0.1/honeycomb_0.0.1_linux_amd64.tar.gz"
        sha256 "a1ef67ba167ac26cb7ac1141fd228f61f4a10fc9a062a887a34b4eb0d40088ad"

        def install
          bin.install "honeycomb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/honeycomb/releases/download/v0.0.1/honeycomb_0.0.1_linux_arm64.tar.gz"
        sha256 "c89854f4ac52f7b250681eeb724a5db6a85c8f5e1020636fb7d70cca3d893dfa"

        def install
          bin.install "honeycomb"
        end
      end
    end
  end
end
