# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honeycomb < Formula
  desc "honeycomb - Nostr client CLI application for cross-platform"
  homepage ""
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nao1215/honeycomb/releases/download/v0.0.2/honeycomb_0.0.2_darwin_amd64.tar.gz"
      sha256 "ca8389944cdd640434255848d25bcb23fed8f700b03f630297a2518622725f32"

      def install
        bin.install "honeycomb"
      end
    end
    on_arm do
      url "https://github.com/nao1215/honeycomb/releases/download/v0.0.2/honeycomb_0.0.2_darwin_arm64.tar.gz"
      sha256 "8bbfbff84e08f41ea6e106be9a7c84eb85d6080a9c082b906103a2ea70d10e9b"

      def install
        bin.install "honeycomb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/honeycomb/releases/download/v0.0.2/honeycomb_0.0.2_linux_amd64.tar.gz"
        sha256 "32b3e6b0044f72a492d49c9744e325a30f09a7d9ab4720fd74d1b68470fcf9c6"

        def install
          bin.install "honeycomb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/honeycomb/releases/download/v0.0.2/honeycomb_0.0.2_linux_arm64.tar.gz"
        sha256 "b9e599b093c7fe0cdd3ce1857ab825b21c1089341aedf61b97e638d21f6642bf"

        def install
          bin.install "honeycomb"
        end
      end
    end
  end
end
