# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hottest < Formula
  desc "hottest - user-friendly 'go test' that extracts error messages."
  homepage ""
  version "0.1.2"
  license "BSD 3-Clause License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/hottest/releases/download/v0.1.2/hottest_0.1.2_darwin_amd64.tar.gz"
      sha256 "534a8dc7ab54a9b51d98f335e9e10debd9a09e787950b8d0f310e9b8db72491f"

      def install
        bin.install "hottest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/hottest/releases/download/v0.1.2/hottest_0.1.2_darwin_arm64.tar.gz"
      sha256 "82fcd72f1d57bb25276b1f1cd880463e437ffe628ea57862f356fb5fe8649cfc"

      def install
        bin.install "hottest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/hottest/releases/download/v0.1.2/hottest_0.1.2_linux_amd64.tar.gz"
      sha256 "86508cdfae99d6ff08ee55dd215b086e3eaa135d00fe551ad59aa69d92957ab1"

      def install
        bin.install "hottest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/hottest/releases/download/v0.1.2/hottest_0.1.2_linux_arm64.tar.gz"
      sha256 "c08060c70dd32f993d062b090bd569a50543e807efd5628f0eb71939cf84bd79"

      def install
        bin.install "hottest"
      end
    end
  end
end
