# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurrah < Formula
  desc "hurrah - API Gateway"
  homepage ""
  version "0.0.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/nao1215/hurrah/releases/download/v0.0.0/hurrah_0.0.0_darwin_amd64.tar.gz"
      sha256 "00162745fb771fa692fceb926a7c88e487a11b431ec3290a3c2338eb058f925f"

      def install
        bin.install "hurrah"
      end
    end
    on_arm do
      url "https://github.com/nao1215/hurrah/releases/download/v0.0.0/hurrah_0.0.0_darwin_arm64.tar.gz"
      sha256 "e98dceea23b85ef4ff505ab6db1527682b8b136a060035e7b80be9be8eb921f9"

      def install
        bin.install "hurrah"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/hurrah/releases/download/v0.0.0/hurrah_0.0.0_linux_amd64.tar.gz"
        sha256 "a903841c63823aea8f188fa540fc179e99737e1ec5dcb0c71a739e97f3038615"

        def install
          bin.install "hurrah"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nao1215/hurrah/releases/download/v0.0.0/hurrah_0.0.0_linux_arm64.tar.gz"
        sha256 "c2c97329d68ced23b94c9c353b2d9d074eb6248621bb877840da63248a37e078"

        def install
          bin.install "hurrah"
        end
      end
    end
  end
end
