# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jose < Formula
  desc "jose - CLI tool for JOSE (JSON Object Signing and Encryption)"
  homepage ""
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/jose/releases/download/v0.0.8/jose_0.0.8_darwin_amd64.tar.gz"
      sha256 "f461bd6ab0f636c6e575f0a47b85a74c1714c9a6f7416ad2b20d17f0a6deb375"

      def install
        bin.install "jose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/jose/releases/download/v0.0.8/jose_0.0.8_darwin_arm64.tar.gz"
      sha256 "dbf9405f0ee29e9aca5996bb48bf1725080cd5835db3c362441dc3af072bddc1"

      def install
        bin.install "jose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/jose/releases/download/v0.0.8/jose_0.0.8_linux_amd64.tar.gz"
      sha256 "179a0f7cf3966ac69b08802b0100dc8b39fdbe2bd3c95a15682d780044f29c18"

      def install
        bin.install "jose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/jose/releases/download/v0.0.8/jose_0.0.8_linux_arm64.tar.gz"
      sha256 "c04309e77bcbd376b519f1908db2142b97c7a29672b4ebe66ea8ab2a0637ac1f"

      def install
        bin.install "jose"
      end
    end
  end
end
