# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimixbox < Formula
  desc "MimixBox - mimic BusyBox on Linux"
  homepage ""
  version "0.33.8"
  license "Apache-2.0 license"
  depends_on :linux

  if Hardware::CPU.intel?
    url "https://github.com/nao1215/mimixbox/releases/download/v0.33.8/mimixbox_0.33.8_linux_amd64.tar.gz"
    sha256 "bd8a08757d486782afde5fda6010e70e1b6a783a8711123a2f97088a33a7075b"

    def install
      bin.install "mimixbox"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nao1215/mimixbox/releases/download/v0.33.8/mimixbox_0.33.8_linux_arm64.tar.gz"
    sha256 "13fe64e0d6ab1fed3f5fccbc9636f90fb5c1b67e5ca60b55cafd6c038ec3e6e4"

    def install
      bin.install "mimixbox"
    end
  end
end
