# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onionscan < Formula
  desc "OnionScan - Security auditing tool for Tor hidden services (.onion addresses)"
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/onionscan/releases/download/v0.1.1/onionscan_0.1.1_darwin_amd64.tar.gz"
      sha256 "77d66823e8cb02c25284e5281ef204473fc5383cce8941c3134a13ce2cdd56ea"

      def install
        bin.install "onionscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/onionscan/releases/download/v0.1.1/onionscan_0.1.1_darwin_arm64.tar.gz"
      sha256 "9ce9355160d1645a11c9d89637f636d9fc8fd1289231e6520b20d5b451295923"

      def install
        bin.install "onionscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/onionscan/releases/download/v0.1.1/onionscan_0.1.1_linux_amd64.tar.gz"
      sha256 "a8da4578e1f846835c5b8be2d49beef516f3d02e2abddefb842153dc2c1297ac"
      def install
        bin.install "onionscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/onionscan/releases/download/v0.1.1/onionscan_0.1.1_linux_arm64.tar.gz"
      sha256 "cf0cba234674f68ce29112be5b073ec26a04880e9f92b538e4577d9a3362a5ed"
      def install
        bin.install "onionscan"
      end
    end
  end
end
