# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqly < Formula
  desc "SQL shell for CSV/TSV/LTSV/JSON/JSONL/Parquet/Excel/ACH/Fedwire + compressed"
  homepage ""
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/sqly/releases/download/v1.5.0/sqly_1.5.0_darwin_amd64.tar.gz"
      sha256 "3a12fec8bfebca4a81c10eb803db72320cbdc6d2f6f91b4eb4320a7170b1871d"

      define_method(:install) do
        bin.install "sqly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/sqly/releases/download/v1.5.0/sqly_1.5.0_darwin_arm64.tar.gz"
      sha256 "e5a42f4f9696c82b4fda2e7283981ce5109b02b2e0a6bc05059dcd16e41ed4b6"

      define_method(:install) do
        bin.install "sqly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/sqly/releases/download/v1.5.0/sqly_1.5.0_linux_amd64.tar.gz"
      sha256 "253efdf00cf242c7a347f7ad48e40bfee6fd109b9fbcf538e7648b5f8f64d8f5"
      define_method(:install) do
        bin.install "sqly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/sqly/releases/download/v1.5.0/sqly_1.5.0_linux_arm64.tar.gz"
      sha256 "8dcb7c8825eda8434a04a2f73caf2edd15013daeeaa1a7e3b38dd7193e2f6c51"
      define_method(:install) do
        bin.install "sqly"
      end
    end
  end
end
