# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqly < Formula
  desc "SQL shell for CSV/TSV/LTSV/JSON/JSONL/Parquet/Excel/ACH/Fedwire + compressed"
  homepage ""
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nao1215/sqly/releases/download/v1.7.1/sqly_1.7.1_darwin_amd64.tar.gz"
      sha256 "87fc1967487ea7a30c9d419abad60c2b2763698cf5d9b5e7644bfed6b89b2e88"

      define_method(:install) do
        bin.install "sqly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nao1215/sqly/releases/download/v1.7.1/sqly_1.7.1_darwin_arm64.tar.gz"
      sha256 "b399b55dbd3856dfc094161209b1d39bf64c906c4fe0b6e7ebadc200d9ecb136"

      define_method(:install) do
        bin.install "sqly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/sqly/releases/download/v1.7.1/sqly_1.7.1_linux_amd64.tar.gz"
      sha256 "e5185ca8a0780028cd52334380290785eb2525b2ee376c1f31c0111adf8fd455"
      define_method(:install) do
        bin.install "sqly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nao1215/sqly/releases/download/v1.7.1/sqly_1.7.1_linux_arm64.tar.gz"
      sha256 "254a9416c8a40c358e637e57a28779a25f5f10c4932c84354237a952021be4c4"
      define_method(:install) do
        bin.install "sqly"
      end
    end
  end
end
