# This file was generated by GoReleaser. DO NOT EDIT.
cask "atago" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "f398b2c950fbcdbf621bac319ffca37ac1c6165e11c137de16b841778a9ea190"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d92462faa47c6c4f1feeb338c9d3a25a967d69bd47c56d10e9f10bbf146ea697"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0dd9ddb65b9403210ff67bc56ec37f65c3485a994917c3df49fe0b23beb0814a"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2b8ab233875ed98c70f3d17d0e2c8580b65578bd132a0e03cfb33f1f0d565aa"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atago"
  desc "Tests CLI behavior from plain YAML: exit codes, output, files, snapshots, and interactive terminals (PTY/TUI)"
  homepage "https://github.com/nao1215/atago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atago"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atago"]
    end
  end

  # No zap stanza required

end
