# This file was generated by GoReleaser. DO NOT EDIT.
cask "atago" do
  version "0.20.1"

  on_macos do
    on_intel do
      sha256 "88626d955366527583727ed146cb48c2b747ee7fb2b55a54218417e1f00ee877"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bb24ac6531cebb1c59da9e1d6e6b250e9c70145870962de20278bad711ba120"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "318f7b5a6cb66373d40d5eed17fed08d8eb560dc51ec63b350b3c2ae3bfa20af"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e2cc4e15a725e61c3d55b489095b927be1ee37e588a924b54ff4de4d13a2585"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atago"
  desc "Tests CLI behavior from plain YAML: exit codes, output, files, snapshots, and interactive terminals (PTY/TUI)"
  homepage "https://github.com/nao1215/atago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atago"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atago"]
    end
  end

  # No zap stanza required

end
