# This file was generated by GoReleaser. DO NOT EDIT.
cask "atago" do
  version "0.25.2"

  on_macos do
    on_intel do
      sha256 "e437b4f7d67d16541daeeb296afc7a7502dfcb58681f04905d8b5b05d0ba2442"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea96433aa260fcad88aa071cacbf8f64ed180587e1defe741df233034b866ddd"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eaed6a6f41d4fa700b6ae6ee1a6d6b9610578fe173c9d5cfb054ff04da855f01"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d702ada0547e471b77d0b7214f49a15c882650784bfda685e415e07c7a56a86f"
      url "https://github.com/nao1215/atago/releases/download/v#{version}/atago_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atago"
  desc "Tests CLI behavior from plain YAML: exit codes, output, files, snapshots, and interactive terminals (PTY/TUI)"
  homepage "https://github.com/nao1215/atago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atago"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atago"]
    end
  end

  # No zap stanza required

end
