# This file was generated by GoReleaser. DO NOT EDIT.
cask "block" do
  version "0.7.3"

  on_macos do
    on_arm do
      sha256 "649f89f243972b927354740f90446e9b27e991a275da32ac82ef91e1a6a91410"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f049e8b9fe7bfec856d97c1d0d1c4fda6b7a65bbb3297f2b3134d60e3d7a626f"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "900daab6af8ab594bc473f99f6e493a7fa7cd608d4bbb062212b036ea40d9cd4"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7cf09251bdeacd01cd227e081efeee8c6a57fec020f6cd6d5ddd130cfc78992c"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_amd64.tar.gz"
    end
  end

  name "block"
  desc "Lock your blockchain toolchain: pin Foundry, Hermes and friends per project and reproduce them in CI"
  homepage "https://github.com/nao1215/block"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "block"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/block"]
    end
  end

  # No zap stanza required
end
