# This file was generated by GoReleaser. DO NOT EDIT.
cask "block" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "9e6cc7e058a834ff922f8de9bc8f883e18513d8158d53d6358e178cf41e53eff"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa2ea6176fa109fc317ead183b33081668965600be0a9b3c5fc8a1172e0639be"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08013b6abf1216e9670b43e53dcf942de7216dd9a0af8f31e614a2006a7aa22a"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "79118e130f3d89feb7535296243db643a06284fe2001bbfa12093b15709f7adc"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_arm64.tar.gz"
    end
  end

  name "block"
  desc "Lock your blockchain toolchain: pin Foundry, Hermes and friends per project and reproduce them in CI"
  homepage "https://github.com/nao1215/block"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "block"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/block"]
    end
  end

  # No zap stanza required

end
