# This file was generated by GoReleaser. DO NOT EDIT.
cask "block" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "ee087781deb2e776953dfcc2676cdd6623fb4512d31a520e1a8c3e7aee3e0292"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3cbff4e8f5dfd27015d89b9c7104c32caa776560c3a17d44d2fd8edefa927fe5"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74bab1478d93d8bc9af06e64993b14ef666c75623e510e224bc4385127f3becc"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff28351603803cee7aa745ccf428cadc449a8ab3efc87ee107d052c84740734c"
      url "https://github.com/nao1215/block/releases/download/v#{version}/block_#{version}_linux_amd64.tar.gz"
    end
  end

  name "block"
  desc "Lock your blockchain toolchain: pin Foundry, Hermes and friends per project and reproduce them in CI"
  homepage "https://github.com/nao1215/block"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "block"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/block"]
    end
  end

  # No zap stanza required
end
