# This file was generated by GoReleaser. DO NOT EDIT.
cask "himorime" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e8b0519d9fae0c933455f6491fd87761974af9e36922094735a1c143081e15a6"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2022ad0bc177980655ff502b152c7e382eb7135bfcc2a80fcf1ca0e57507ca42"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f1287756621b24d15b6934233c1ef8b1b5e5ff9575ab99d5fbe11e48a6c3248"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a07491e39f841b030ceafffc2681ac8d9e655beb8dcfeee7241505111212254"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "himorime"
  desc "Performance budgets and regression checks for command-line programs"
  homepage "https://nao1215.github.io/himorime/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "himorime"
  bash_completion "completions/himorime.bash"
  fish_completion "completions/himorime.fish"
  zsh_completion "completions/himorime.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/himorime"]
    end
  end

  # No zap stanza required

end
