# This file was generated by GoReleaser. DO NOT EDIT.
cask "himorime" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "92fc8466d032179a3c3910ece885a1ffceb79e86ace99375ebf8eb8f4b7fca95"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69d300be39b9fb5359ee0e0d6bfca5fc76f169476f77e506f76fd48ad37430b5"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e0806f4e5d3066eb3bf0d8c781b75c89ed00be8e59d1766d0300574eb7265f9"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c859ebdbc76616459f0ff02cedbf15b575bb11f11dcc8132db26736aebfb580"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "himorime"
  desc "Performance budgets and regression checks for command-line programs"
  homepage "https://nao1215.github.io/himorime/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "himorime"
  bash_completion "completions/himorime.bash"
  fish_completion "completions/himorime.fish"
  zsh_completion "completions/himorime.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/himorime"]
    end
  end

  # No zap stanza required

end
