# This file was generated by GoReleaser. DO NOT EDIT.
cask "himorime" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8b46b4147a14c0ea9ed2dcb5afe7eb406b00fa32deb6fd16dcd1787f75b90e64"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e13c0456f6c5c8b2dcd69c06fecdeb1b9fbf8c011f34c81dd5306d5b00e47b6c"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ce8a5979acc1f939eb877691d06b037fb271da48db5facf82dcd4607a427b41"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c2c252bbe2630e2ddf3d703dc149e352c8a2892e1b9498e37b4abeb3c679a97"
      url "https://github.com/nao1215/himorime/releases/download/v#{version}/himorime_#{version}_linux_arm64.tar.gz"
    end
  end

  name "himorime"
  desc "Performance budgets and regression checks for command-line programs"
  homepage "https://nao1215.github.io/himorime/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "himorime"
  bash_completion "completions/himorime.bash"
  fish_completion "completions/himorime.fish"
  zsh_completion "completions/himorime.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/himorime"]
    end
  end

  # No zap stanza required

end
