# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsonize" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "2602c692426ed8101c6b15257ccdec8145472b1b1cd19270779614306aa68366"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ac18883ed508fa349be4ee91612767e1a51085c9d9be142c07db4bc8547fc9f"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c518e35e5984525a7941c660728d883c3e9ede9ca379bd8bdc0d1d7a34bc76d"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "540f633b4fa2176cde7972165ca207b63cd7f0f30b4a718cb1af994f58aab8f2"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jsonize"
  desc "Make JSON from command output, files and arguments for the next command"
  homepage "https://github.com/nao1215/jsonize"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jz"]
    end
  end

  # No zap stanza required

end
