# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsonize" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "828703e8b69e769d0585bb20d6ab70841a4d38f5b80d867540c61f56cd499998"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f27405754775c237f5a446c1898ce0a749e8936252164ed1dafa809256a415f"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "795c48b644857a9d9971dce3a659d2c723f19de649ccf427856fbdeaabb9ba02"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be834112b202236f7cb203595340adb26fe5fc9c6464ce9225b0f28e665ea22c"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jsonize"
  desc "Turn command output into JSON"
  homepage "https://github.com/nao1215/jsonize"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jz"]
    end
  end

  # No zap stanza required

end
