# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsonize" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "6f78e0a17c8d8a09b68222ae5478afd74a3943733322834957d612b2a3441f54"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90750f63306e20b6b4823d1a86b7f662fdf401b151ea952ba2be90b23cd73832"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19a15115f50b32f5543d2d97aaac6f62f9c3f4a757acc5430ffcf5d760a66e5d"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7891d8ffb42bd4f5426b97d8a6a0c463f343d03f9cee4f1c16e7fc80e7d95baf"
      url "https://github.com/nao1215/jsonize/releases/download/v#{version}/jsonize_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jsonize"
  desc "Make JSON from command output, files and arguments for the next command"
  homepage "https://github.com/nao1215/jsonize"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jz"]
    end
  end

  # No zap stanza required

end
