# This file was generated by GoReleaser. DO NOT EDIT.
cask "onionscan" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "25b0f8920bbdcdfd98ce6ba3b2dd1bbd28a0649a46fb444e27db84cfac9cec0e"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91e141fa50ef7c62d3cd295f1c35d55a4fea3754f1e97f5b336a631a4815f4cf"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b7c8917dac4f3c48a074ad9b291b6c63f07dc38e171892c46435d66db9dab732"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "859b13ddf9cdb95be71676279c77ffe6f31805e0306a85b95fa612a456006c41"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_amd64.tar.gz"
    end
  end

  name "onionscan"
  desc "OnionScan - Security auditing tool for Tor hidden services (.onion addresses)"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onionscan"

  # No zap stanza required
end
