# This file was generated by GoReleaser. DO NOT EDIT.
cask "onionscan" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "bbc763a235fa2402ada122714f7ee75f986e79b957cae19cc008c9cd413dde91"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc9cbcc638d27001ca5d5a6cfbd1c33ca5428cd911dfaad81cd1016de5981b14"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "edc0c7668b2e6d25b4c79633c306e63c2bbf0c7e01cfd026e780b40c7adf0534"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6dfa4e61a3d428904d5b76efd949bee0b7baa2404280aba30715dbd69e00f463"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "onionscan"
  desc "OnionScan - Security auditing tool for Tor hidden services (.onion addresses)"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onionscan"

  # No zap stanza required

end
