# This file was generated by GoReleaser. DO NOT EDIT.
cask "onionscan" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "77d9496adf758f2a173c12b9510f783d34cefdb277b50269b1ffb3ecf5d6a0e1"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ecdfbbcb1393b739f29795aa507c1f0d4e583a0fed9d31ae2756f01f139f88a"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9cdd043b8ec47721d7fc6e3f4be98694ea570310276cecf600d0f9bc47b1fd4"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a89fdb06b5949a4f50d49d720b0f5247acdaeae9fe4894c0f8af8b1605f997a"
      url "https://github.com/nao1215/onionscan/releases/download/v#{version}/onionscan_#{version}_linux_amd64.tar.gz"
    end
  end

  name "onionscan"
  desc "OnionScan - Security auditing tool for Tor hidden services (.onion addresses)"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onionscan"

  # No zap stanza required
end
