# This file was generated by GoReleaser. DO NOT EDIT.
cask "rabbitrun" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "e7a257b923a501f24c354f6fea57477223aa15cf2827cc27ba15d2667cce4d0d"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c401a3ee62bd279464587cc668ddb4c45be87c73aba3fbafe169ab4170f8145d"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa0e1fef8b1fc63590f0ee6cbc9cb2ad7f519245eb163235e9903dd51a840e3d"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5036602bf5ee3a6bd8bc36eff09ce37eea89ff108592bf5d4d3b9812117577d1"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rabbitrun"
  desc "A runner game with anime girls for Windows, macOS, and Linux"
  homepage "https://github.com/nao1215/rabbitrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rabbitrun"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rabbitrun"]
    end
  end

  # No zap stanza required
end
