# This file was generated by GoReleaser. DO NOT EDIT.
cask "rabbitrun" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "560f1cdb82dffd47b1a72f4ab6e0a456fe6554803a9aadee54cebed5c22a01d8"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "28f6190b453ab62c23873361bc52fdfc6250ffd41c971337115af0e6fb3d0e43"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "716fde5bb4a163b8186d39d41231017d8f870b215bd20888570e86544968379a"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceb3a65ad2a46a4a165761babecb2209989f3734f7fb642ad343c5ebdde3b526"
      url "https://github.com/nao1215/rabbitrun/releases/download/v#{version}/rabbitrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rabbitrun"
  desc "A runner game with anime girls for Windows, macOS, and Linux"
  homepage "https://github.com/nao1215/rabbitrun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rabbitrun"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rabbitrun"]
    end
  end

  # No zap stanza required
end
